### ISSUE TITLE
Metadata module

### ISSUE THREAD

**Issue by kbobrowski** [Qimia/fastGQL#1]
Metadata should be processed in another module, aiming for:

`DatabaseSchema database = MetadataUtils.createDatabaseSchema(client);`

**Comment by MingyiZhang** [comment]
In branch `metadata-to-schema`, in module `metadata`, a `MetadataUtils` class and the createDatabaseSchema(Connection connection) is implemented. I use JDBC to extract the database metadata instead of PgPool client.
